// Tool definitions and categories

export type ToolCategory = 'ai' | 'pdf' | 'office' | 'media';

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  badge: string;
  gradient: string;
  href: string;
  category: ToolCategory;
  isServerEnabled?: boolean;
  color?: string; // Added for compatibility with ToolsCatalog
}

export type ToolMeta = Tool;

export const AI_TOOLS: Tool[] = [
  {
    id: 'ai-chat',
    name: 'AI Chat',
    description: 'Talk with Halo AI assistant',
    icon: '💬',
    badge: 'AI',
    gradient: 'from-purple-500 to-pink-500',
    href: '/ai-workspace/chat',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-purple-500',
  },
  {
    id: 'ai-document-summary',
    name: 'AI Document Summary',
    description: 'Summarize long documents instantly',
    icon: '📄',
    badge: 'AI',
    gradient: 'from-blue-500 to-cyan-500',
    href: '/ai-workspace/document-summary',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-blue-500',
  },
  {
    id: 'ai-image-studio',
    name: 'AI Image Studio',
    description: 'Generate and edit images with AI',
    icon: '🎨',
    badge: 'AI',
    gradient: 'from-pink-500 to-rose-500',
    href: '/ai-workspace/image-studio',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-pink-500',
  },
  {
    id: 'ai-translator',
    name: 'AI Translator',
    description: 'Translate to 100+ languages',
    icon: '🌐',
    badge: 'AI',
    gradient: 'from-green-500 to-emerald-500',
    href: '/ai-workspace/translator',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-green-500',
  },
  {
    id: 'ai-rewriter',
    name: 'AI Rewriter',
    description: 'Rewrite and improve your content',
    icon: '✍️',
    badge: 'AI',
    gradient: 'from-orange-500 to-amber-500',
    href: '/ai-workspace/rewriter',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-orange-500',
  },
  {
    id: 'ai-insights',
    name: 'AI Insights',
    description: 'Extract insights from data',
    icon: '📊',
    badge: 'AI',
    gradient: 'from-violet-500 to-purple-500',
    href: '/ai-workspace/insights',
    category: 'ai',
    isServerEnabled: true,
    color: 'bg-violet-500',
  },
];

export const PDF_TOOLS: Tool[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one',
    icon: '📑',
    badge: 'PDF',
    gradient: 'from-red-500 to-orange-500',
    href: '/tools/merge-pdf',
    category: 'pdf',
    color: 'bg-red-500',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract pages from PDF',
    icon: '✂️',
    badge: 'PDF',
    gradient: 'from-cyan-500 to-blue-500',
    href: '/tools/split-pdf',
    category: 'pdf',
    color: 'bg-cyan-500',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size',
    icon: '🗜️',
    badge: 'PDF',
    gradient: 'from-green-500 to-teal-500',
    href: '/tools/compress-pdf',
    category: 'pdf',
    color: 'bg-green-500',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove PDF password protection',
    icon: '🔓',
    badge: 'PDF',
    gradient: 'from-emerald-500 to-teal-500',
    href: '/tools/unlock-pdf',
    category: 'pdf',
    color: 'bg-emerald-500',
  },
  {
    id: 'pdf-password',
    name: 'PDF Password',
    description: 'Add or remove PDF password',
    icon: '🔐',
    badge: 'PDF',
    gradient: 'from-violet-500 to-purple-500',
    href: '/tools/pdf-password',
    category: 'pdf',
    color: 'bg-violet-500',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Images',
    description: 'Convert PDF pages to images',
    icon: '🖼️',
    badge: 'PDF',
    gradient: 'from-purple-500 to-violet-500',
    href: '/tools/pdf-to-image',
    category: 'pdf',
    color: 'bg-purple-500',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages by any angle',
    icon: '🔄',
    badge: 'PDF',
    gradient: 'from-pink-500 to-rose-500',
    href: '/tools/rotate-pdf',
    category: 'pdf',
    color: 'bg-pink-500',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted PDF files',
    icon: '🔧',
    badge: 'PDF',
    gradient: 'from-amber-500 to-yellow-500',
    href: '/tools/repair-pdf',
    category: 'pdf',
    color: 'bg-amber-500',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text watermarks to PDF',
    icon: '💧',
    badge: 'PDF',
    gradient: 'from-sky-500 to-blue-500',
    href: '/tools/add-watermark',
    category: 'pdf',
    color: 'bg-sky-500',
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to PDF',
    icon: '🔢',
    badge: 'PDF',
    gradient: 'from-indigo-500 to-purple-500',
    href: '/tools/add-page-numbers',
    category: 'pdf',
    color: 'bg-indigo-500',
  },
];

export const OFFICE_TOOLS: Tool[] = [
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF',
    icon: '📄',
    badge: 'OFFICE',
    gradient: 'from-blue-600 to-blue-400',
    href: '/tools/word-to-pdf',
    category: 'office',
    color: 'bg-blue-600',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    icon: '📊',
    badge: 'OFFICE',
    gradient: 'from-green-600 to-green-400',
    href: '/tools/excel-to-pdf',
    category: 'office',
    color: 'bg-green-600',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint to PDF',
    icon: '📽️',
    badge: 'OFFICE',
    gradient: 'from-orange-600 to-orange-400',
    href: '/tools/ppt-to-pdf',
    category: 'office',
    color: 'bg-orange-600',
  },
];

export const MEDIA_TOOLS: Tool[] = [
  {
    id: 'jpeg-compressor',
    name: 'JPEG Compressor',
    description: 'Compress JPEG photos',
    icon: '📸',
    badge: 'MEDIA',
    gradient: 'from-orange-500 to-red-500',
    href: '/tools/jpeg-compressor',
    category: 'media',
    color: 'bg-orange-500',
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    description: 'Reduce video file size',
    icon: '🎬',
    badge: 'MEDIA',
    gradient: 'from-purple-500 to-pink-500',
    href: '/tools/video-compressor',
    category: 'media',
    color: 'bg-purple-500',
  },
  {
    id: 'png-compressor',
    name: 'PNG Compressor',
    description: 'Optimize PNG images',
    icon: '🖼️',
    badge: 'MEDIA',
    gradient: 'from-purple-500 to-pink-500',
    href: '/tools/png-compressor',
    category: 'media',
    color: 'bg-purple-500',
  },
  {
    id: 'jpeg-to-png',
    name: 'JPEG to PNG',
    description: 'Convert JPEG to PNG format',
    icon: '🔄',
    badge: 'MEDIA',
    gradient: 'from-blue-500 to-cyan-500',
    href: '/tools/jpeg-to-png',
    category: 'media',
    color: 'bg-blue-500',
  },
  {
    id: 'gif-compressor',
    name: 'GIF Compressor',
    description: 'Reduce GIF file size',
    icon: '🎞️',
    badge: 'MEDIA',
    gradient: 'from-pink-500 to-rose-500',
    href: '/tools/gif-compressor',
    category: 'media',
    color: 'bg-pink-500',
  },
  {
    id: 'webp-compressor',
    name: 'WebP Compressor',
    description: 'Compress WebP images',
    icon: '🌐',
    badge: 'MEDIA',
    gradient: 'from-emerald-500 to-teal-500',
    href: '/tools/webp-compressor',
    category: 'media',
    color: 'bg-emerald-500',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce any image file size',
    icon: '🗜️',
    badge: 'MEDIA',
    gradient: 'from-blue-500 to-cyan-500',
    href: '/tools/image-compressor',
    category: 'media',
    color: 'bg-blue-500',
  },
  {
    id: 'video-downloader',
    name: 'Video Downloader',
    description: 'Download and convert videos',
    icon: '📥',
    badge: 'MEDIA',
    gradient: 'from-green-500 to-emerald-500',
    href: '/tools/video-downloader',
    category: 'media',
    color: 'bg-green-500',
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Crop and resize images',
    icon: '✂️',
    badge: 'MEDIA',
    gradient: 'from-cyan-500 to-blue-500',
    href: '/tools/crop-image',
    category: 'media',
    color: 'bg-cyan-500',
  },
  {
    id: 'crop-png',
    name: 'Crop PNG',
    description: 'Crop PNG with transparency',
    icon: '🔲',
    badge: 'MEDIA',
    gradient: 'from-indigo-500 to-purple-500',
    href: '/tools/crop-png',
    category: 'media',
    color: 'bg-indigo-500',
  },
  {
    id: 'crop-webp',
    name: 'Crop WebP',
    description: 'Crop modern WebP images',
    icon: '🌐',
    badge: 'MEDIA',
    gradient: 'from-teal-500 to-cyan-500',
    href: '/tools/crop-webp',
    category: 'media',
    color: 'bg-teal-500',
  },
  {
    id: 'crop-jpg',
    name: 'Crop JPG',
    description: 'Crop JPEG images',
    icon: '📐',
    badge: 'MEDIA',
    gradient: 'from-amber-500 to-orange-500',
    href: '/tools/crop-jpg',
    category: 'media',
    color: 'bg-amber-500',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to any dimension',
    icon: '📏',
    badge: 'MEDIA',
    gradient: 'from-violet-500 to-purple-500',
    href: '/tools/image-resizer',
    category: 'media',
    color: 'bg-violet-500',
  },
  {
    id: 'resize-png',
    name: 'Resize PNG',
    description: 'Resize PNG images',
    icon: '🔷',
    badge: 'MEDIA',
    gradient: 'from-blue-600 to-blue-400',
    href: '/tools/resize-png',
    category: 'media',
    color: 'bg-blue-600',
  },
  {
    id: 'resize-jpg',
    name: 'Resize JPG',
    description: 'Resize JPEG images',
    icon: '🔶',
    badge: 'MEDIA',
    gradient: 'from-orange-600 to-yellow-400',
    href: '/tools/resize-jpg',
    category: 'media',
    color: 'bg-orange-600',
  },
  {
    id: 'resize-webp',
    name: 'Resize WebP',
    description: 'Resize WebP images',
    icon: '🔷',
    badge: 'MEDIA',
    gradient: 'from-cyan-600 to-teal-400',
    href: '/tools/resize-webp',
    category: 'media',
    color: 'bg-cyan-600',
  },
  {
    id: 'bulk-resize',
    name: 'Bulk Resize',
    description: 'Resize multiple images at once',
    icon: '📦',
    badge: 'MEDIA',
    gradient: 'from-emerald-600 to-green-400',
    href: '/tools/bulk-resize',
    category: 'media',
    color: 'bg-emerald-600',
  },
];

export const ALL_TOOLS = [...AI_TOOLS, ...PDF_TOOLS, ...OFFICE_TOOLS, ...MEDIA_TOOLS];

// Export aliases for compatibility with ToolsCatalog imports
export const allTools = ALL_TOOLS;
export const aiTools = AI_TOOLS;
export const pdfTools = PDF_TOOLS;
export const officeTools = OFFICE_TOOLS;
export const mediaTools = MEDIA_TOOLS;
